mysql:
  image: mysql:5.6.34
  ports:
    - "3002:3002"
  volumes_from:
    - dbdata
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=dev

dbdata:
  image: tianon/true
  volumes:
    - /var/lib/mysql

web:
  build: .
  environment:
    - RAILS_ENV=development
    - ELASTICSEARCH_URL=http://elasticsearch:9200
  ports:
    - '3000:3000'
  volumes_from:
    - appdata
  links:
    - "mysql"
    - elasticsearch

appdata:
  image: tianon/true
  volumes:
    - ".:/workspace"

elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.0
    environment:
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - "es-data:/usr/share/elasticsearch/data"
